[client]
showSidebarNavigation = false

[theme]
base="dark"
primaryColor="#4b0082"  # indigo
secondaryBackgroundColor="#2e2e2e"  # lighter shade
textColor="#e0e0e0"  # light gray
font="serif"  # serif font

